apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-bot-account
  name: deploy-bot-account
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: deploy-bot-account
status:
  loadBalancer: {}