# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: test-sliit
#   name: test-sliit
# spec:
#   ports:
#     - port: 3000
#       protocol: TCP
#       targetPort: 3000
#   selector:
#     app: test-sliit
# status:
#   loadBalancer: {}


apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE
spec:
  type: LoadBalancer
  selector:
    app: $GKE_APP_NAME
  ports:
  - port: 80
    targetPort: 80